[project]
name = "multivisor-web"
version = "0.1.0"
description = "Sinclair group's multivisor web dashboard deployment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "multivisor[cli,web] @ git+https://github.com/SinclairQuantumLab/multivisor.git@refactor/git-package-deployment",
]
