; Supervisor config file for program(s)
; copy this file into /etc/supervisor/conf.d/ folder

[program:multivisor]
command=/home/roku/multivisor/Startup_bash
environment=PYTHONUNBUFFERED=1 ; let stdout logged in real time for python app
user=roku
autostart=true
autorestart=true
stdout_logfile=/etc/supervisor/logs/multivisor_out.log
stderr_logfile=/etc/supervisor/logs/multivisor_err.log
